# Generated by Django 4.2.2 on 2023-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('fecha_evento', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
