# Generated by Django 4.2.2 on 2023-07-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_evento'),
        ),
    ]
