# Generated by Django 4.2.2 on 2023-07-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='modalidad',
            field=models.CharField(choices=[('V', 'Virtual'), ('P', 'Presencial')], default='P', max_length=1),
        ),
    ]
